config/routes.rb
Rails.application.routes.draw do
  # Root path to the form for creating a new short URL
  root 'short_urls#new'

  # Resources for short URLs to handle creation and listing
  resources :short_urls, only: [:new, :create, :index]

  # Redirect route for the short path
  get '/:short_path', to: 'short_urls#redirect', as: :short_url

  # Stats route for viewing clicks statistics
  get '/short_urls/:short_path/click_logs', to: 'short_urls#click_logs', as: 'short_url_click_logs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click_log.rb
class ClickLog < ApplicationRecord
  belongs_to :short_url
end

app/models/original_url.rb
class OriginalUrl < ApplicationRecord
  has_many :short_urls

  validates :url, presence: true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  belongs_to :original_url
  has_many :click_logs

  validates :short_path, length: { maximum: 15 }, uniqueness: true

  before_validation :generate_short_path, on: :create

  private

  def generate_short_path
    self.short_path = generate_unique_short_path if self.short_path.blank?
  end

  def generate_unique_short_path
    loop do
      random_path = Base58.encode(SecureRandom.random_number(2147483647)).first(8)
      break random_path unless ShortUrl.exists?(short_path: random_path)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  def redirect
    @short_url = ShortUrl.find_by(short_path: params[:short_path])
  
    if @short_url.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found
    else
      ClickLog.create!(short_url: @short_url, ip_address: request.remote_ip, clicked_at: Time.now)
      redirect_to @short_url.original_url.url
    end
  end
  
  def click_logs
    @short_url = ShortUrl.find_by(short_path: params[:short_path])
    @click_logs = @short_url.click_logs if @short_url
    @original_url = @short_url.original_url.url if @short_url
    @total_clicks = @click_logs.count if @click_logs

    render :click_logs, status: @short_url ? :ok : :not_found
  end
  
  def new
    @short_url = ShortUrl.new
    @short_urls = ShortUrl.all.order(created_at: :desc).includes(:click_logs)
  end

  def create
    return if short_url_params[:original_url].blank?

    @short_url = build_short_url_from_params

    if @short_url.save
      redirect_to new_short_url_path, notice: 'Short URL created successfully.'
    else
      @short_urls = ShortUrl.all.order(created_at: :desc).includes(:click_logs)
      flash.now[:error] = 'Failed to create Short URL.'
      render :new
    end
  end

  def index
    @short_urls = ShortUrl.all
  end
  
  private
  
  def build_short_url_from_params
    original_url = OriginalUrl.find_or_create_by!(url: short_url_params[:original_url])
    original_url.short_urls.build(short_path: short_url_params[:short_path])
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    nil
  end
  
  def short_url_params
    params.require(:short_url).permit(:original_url, :short_path)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 mb-24 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/short_urls/click_logs.html.erb
<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-4">
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold text-white mb-4">Click Logs for /<%= @short_url.short_path %></h1>
    <%= link_to 'Back', :back, class: "btn-primary py-3 rounded-lg" %>
  </div>

  <p class="text-lg text-gray-300 mb-4">Original URL: <%= @original_url %></p>
  <p class="text-lg text-gray-300 mb-4">Total Clicks: <%= @total_clicks %></p>

  <% if @click_logs.empty? %>
    <div class="card shadow overflow-hidden sm:rounded-lg p-4">
      <p class="text-gray-500">No click logs found.</p>
    </div>
  <% else %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <% @click_logs.each do |log| %>
        <div class="card shadow overflow-hidden sm:rounded-lg p-4">
          <div class="mb-2">
            <h3 class="text-lg leading-6 font-medium text-gray-200">IP Address:</h3>
            <p class="mt-1 text-sm text-gray-300"><%= log.ip_address %></p>
          </div>
          <div>
            <h3 class="text-lg leading-6 font-medium text-gray-200">Clicked At:</h3>
            <p class="mt-1 text-sm text-gray-300"><%= log.clicked_at.strftime("%B %d, %Y %H:%M") %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/short_urls/index.html.erb
<h1>Shortened URLs</h1>
<table>
  <thead>
    <tr>
      <th>Original URL</th>
      <th>Short Path</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @short_urls.each do |short_url| %>
      <tr>
        <td><%= short_url.original_url.url %></td>
        <td>
          <% if short_url.short_path.present? %>
            <%= link_to short_url.short_path, short_url_path(short_url.short_path) %>
          <% else %>
            No short path
          <% end %>
        </td>
        <td>
          <% if short_url.short_path.present? %>
            <%= link_to 'Stats', stats_short_url_path(short_url.short_path) %>
          <% else %>
            No short path
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/short_urls/new.html.erb
<div class="w-full">
  <section class="container">
    <h1 class="text-2xl font-bold text-white">URL Shortener</h1>
  </section>
  <section class="container mt-10">
    <div class="card">
      <%= form_with(model: @short_url, local: true) do |form| %>
        <div class="flex gap-5 items-end">
          <div class="w-7/12">
            <%= form.label :original_url, "Original URL", class: "text-white" %>
            <%= form.text_field :original_url, required: true, id: "url", class: "form-input", placeholder: "Enter target URL here" %>
          </div>
          <div class="w-3/12">
            <%= form.label :short_path, "Short Path (Optional)", class: "text-white" %>
            <%= form.text_field :short_path, maxlength: 15, id: "shortPath", class: "form-input", placeholder: "Maximum 15 characters" %>
          </div>
          <div class="w-2/12">
            <%= form.submit "Shorten", class: "btn-primary py-3 rounded-lg w-full" %>
          </div>
        </div>
      <% end %>
    </div>
  </section>

  <section class="container mt-10">
    <h2 class="text-xl font-bold text-white pb-5">Shortened URLs</h2>
    <div class="grid grid-cols-2 gap-4">
      <% @short_urls.each do |short_url| %>
        <div class="card bg-white p-4 shadow-md rounded-lg">
          <h3 class="font-bold">Original URL:</h3>
          <p><%= short_url.original_url.url %></p>
          <h3 class="font-bold">Short Path:</h3>
          <p>/<%= short_url.short_path.present? ? short_url.short_path : "No short path" %></p>
          <h3 class="font-bold">Clicks:</h3>
          <p><%= short_url.click_logs.count %></p>
          <button onclick="copyToClipboard('<%= request.base_url + short_url_path(short_url.short_path) %>')" class="btn btn-secondary">Copy Link</button>
          <%= link_to 'Logs', short_url_click_logs_path(short_url.short_path), class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </section>
</div>

<script>
  function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(function() {
      alert('URL copied to clipboard');
    }, function(err) {
      console.error('Could not copy text: ', err);
    });
  }
</script>